spring:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/bookmanagement?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  shutdown: graceful
  port: 8080

mybatis:
  mapper-locations: classpath:sqlmapper/*.xml

jwt:
  secretKey: ${JWT_SECRET_KEY}

encryption:
  key: ${ENCRYPTION_KEY}